name: Deploy to Nuget

on: ["push"]

env:
  PROJECT_PATH: 'mcs-project/mcs-project.csproj'
  PACKAGE_OUTPUT: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json' 

  jobs:
    deploy:
      name: deploy
      runs-on: 'windows-latest'
      steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        
      - name: 'Install dot net'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
 
# Create new Project
      - name: 'Create Project'
        run: dotnet new console --name OctocatApp

# Pack
      - name: 'Package the project'
        run: dotnet pack --configuration Release

#Publish the package 
      - name: 'Push Project'
        run: dotnet nuget push "bin/Release/OctocatApp.1.0.0.nupkg" --api-key secrets.GIT_ACCESS_TOKEN -s "github"



      
      