name: Deploy to Nuget

on: ["push"]

  jobs:
    deploy:
      name: deploy
      runs-on: 'windows-latest'
      steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        

      - name: 'Install dot net'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      
      - name: 'Restore Packages'
        run: dotnet restore 
