name: Deploy to Nuget

on: ["push"]

env:
  PROJECT_PATH: 'mcs-project/mcs-project.csproj'
  PACKAGE_OUTPUT: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json' 

  jobs:
    deploy:
      name: deploy
      runs-on: 'windows-latest'
      steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        

      - name: 'Install dot net'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      
      - name: 'Restore Packages'
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: 'Restore Packages'
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

      - name: 'Pack Project'
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols --output 

      - name: 'Push Project'
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT }}\*.nupkg -k ${{ secrets.GIT_ACCESS_TOKEN }} -s ${{ NUGET_SOURCE_URL }} 

      
      